# Generated by Django 5.0.6 on 2024-05-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
